#include <vector>

#include <gtest/gtest.h>

#include <lexer.h>

namespace {

void expect_token_eq(
    const Lexer::Token& actual,
    const Lexer::Token& expected,
    std::size_t index
) {
    EXPECT_EQ(actual.type, expected.type) << "Token index: " << index;
    EXPECT_EQ(actual.line, expected.line) << "Token index: " << index;
    EXPECT_EQ(actual.column, expected.column) << "Token index: " << index;
    EXPECT_EQ(actual.lexeme, expected.lexeme) << "Token index: " << index;
}

} // namespace

TEST(LexerTest, AllTokensSnippetMatchesReferenceList) {
    const std::vector<Lexer::Token> ref_token_list = {
        {Lexer::TokenType::TOKEN_INT, 1, 1, "int"},
        {Lexer::TokenType::TOKEN_IDENT, 1, 5, "function"},
        {Lexer::TokenType::TOKEN_L_PARENTH, 1, 13, "("},
        {Lexer::TokenType::TOKEN_R_PARENTH, 1, 14, ")"},
        {Lexer::TokenType::TOKEN_L_BRACE, 1, 16, "{"},
        {Lexer::TokenType::TOKEN_INT, 2, 5, "int"},
        {Lexer::TokenType::TOKEN_IDENT, 2, 9, "a"},
        {Lexer::TokenType::TOKEN_ASSIGN, 2, 11, "="},
        {Lexer::TokenType::TOKEN_DECIMAL_INT, 2, 13, "5"},
        {Lexer::TokenType::TOKEN_SEMICOLON, 2, 14, ";"},
        {Lexer::TokenType::TOKEN_INT, 3, 5, "int"},
        {Lexer::TokenType::TOKEN_IDENT, 3, 9, "b"},
        {Lexer::TokenType::TOKEN_ASSIGN, 3, 11, "="},
        {Lexer::TokenType::TOKEN_DECIMAL_INT, 3, 13, "10"},
        {Lexer::TokenType::TOKEN_SEMICOLON, 3, 15, ";"},
        {Lexer::TokenType::TOKEN_INT, 4, 5, "int"},
        {Lexer::TokenType::TOKEN_IDENT, 4, 9, "c"},
        {Lexer::TokenType::TOKEN_SEMICOLON, 4, 10, ";"},
        {Lexer::TokenType::TOKEN_IDENT, 5, 5, "c"},
        {Lexer::TokenType::TOKEN_ASSIGN, 5, 7, "="},
        {Lexer::TokenType::TOKEN_IDENT, 5, 9, "a"},
        {Lexer::TokenType::TOKEN_ADD, 5, 11, "+"},
        {Lexer::TokenType::TOKEN_IDENT, 5, 13, "b"},
        {Lexer::TokenType::TOKEN_SEMICOLON, 5, 14, ";"},
        {Lexer::TokenType::TOKEN_IDENT, 6, 5, "c"},
        {Lexer::TokenType::TOKEN_ASSIGN, 6, 7, "="},
        {Lexer::TokenType::TOKEN_IDENT, 6, 9, "a"},
        {Lexer::TokenType::TOKEN_SUB, 6, 11, "-"},
        {Lexer::TokenType::TOKEN_IDENT, 6, 13, "b"},
        {Lexer::TokenType::TOKEN_SEMICOLON, 6, 14, ";"},
        {Lexer::TokenType::TOKEN_IDENT, 7, 5, "c"},
        {Lexer::TokenType::TOKEN_ASSIGN, 7, 7, "="},
        {Lexer::TokenType::TOKEN_IDENT, 7, 9, "a"},
        {Lexer::TokenType::TOKEN_MUL, 7, 11, "*"},
        {Lexer::TokenType::TOKEN_IDENT, 7, 13, "b"},
        {Lexer::TokenType::TOKEN_SEMICOLON, 7, 14, ";"},
        {Lexer::TokenType::TOKEN_IDENT, 8, 5, "c"},
        {Lexer::TokenType::TOKEN_ASSIGN, 8, 7, "="},
        {Lexer::TokenType::TOKEN_IDENT, 8, 9, "a"},
        {Lexer::TokenType::TOKEN_DIV, 8, 11, "/"},
        {Lexer::TokenType::TOKEN_IDENT, 8, 13, "b"},
        {Lexer::TokenType::TOKEN_SEMICOLON, 8, 14, ";"},
        {Lexer::TokenType::TOKEN_FOR, 10, 5, "for"},
        {Lexer::TokenType::TOKEN_L_PARENTH, 10, 9, "("},
        {Lexer::TokenType::TOKEN_INT, 10, 10, "int"},
        {Lexer::TokenType::TOKEN_IDENT, 10, 14, "i"},
        {Lexer::TokenType::TOKEN_ASSIGN, 10, 16, "="},
        {Lexer::TokenType::TOKEN_DECIMAL_INT, 10, 18, "0"},
        {Lexer::TokenType::TOKEN_SEMICOLON, 10, 19, ";"},
        {Lexer::TokenType::TOKEN_IDENT, 10, 21, "i"},
        {Lexer::TokenType::TOKEN_LESS, 10, 23, "<"},
        {Lexer::TokenType::TOKEN_IDENT, 10, 25, "b"},
        {Lexer::TokenType::TOKEN_SEMICOLON, 10, 26, ";"},
        {Lexer::TokenType::TOKEN_IDENT, 10, 28, "i"},
        {Lexer::TokenType::TOKEN_ASSIGN, 10, 30, "="},
        {Lexer::TokenType::TOKEN_IDENT, 10, 32, "i"},
        {Lexer::TokenType::TOKEN_ADD, 10, 34, "+"},
        {Lexer::TokenType::TOKEN_DECIMAL_INT, 10, 36, "1"},
        {Lexer::TokenType::TOKEN_R_PARENTH, 10, 37, ")"},
        {Lexer::TokenType::TOKEN_L_BRACE, 10, 39, "{"},
        {Lexer::TokenType::TOKEN_IDENT, 11, 9, "c"},
        {Lexer::TokenType::TOKEN_ASSIGN, 11, 11, "="},
        {Lexer::TokenType::TOKEN_IDENT, 11, 13, "c"},
        {Lexer::TokenType::TOKEN_ADD, 11, 15, "+"},
        {Lexer::TokenType::TOKEN_DECIMAL_INT, 11, 17, "1"},
        {Lexer::TokenType::TOKEN_SEMICOLON, 11, 18, ";"},
        {Lexer::TokenType::TOKEN_R_BRACE, 12, 5, "}"},
        {Lexer::TokenType::TOKEN_IF, 14, 5, "if"},
        {Lexer::TokenType::TOKEN_L_PARENTH, 14, 8, "("},
        {Lexer::TokenType::TOKEN_IDENT, 14, 9, "a"},
        {Lexer::TokenType::TOKEN_GREATER, 14, 11, ">"},
        {Lexer::TokenType::TOKEN_IDENT, 14, 13, "b"},
        {Lexer::TokenType::TOKEN_R_PARENTH, 14, 14, ")"},
        {Lexer::TokenType::TOKEN_L_BRACE, 14, 15, "{"},
        {Lexer::TokenType::TOKEN_IDENT, 15, 9, "c"},
        {Lexer::TokenType::TOKEN_ASSIGN, 15, 11, "="},
        {Lexer::TokenType::TOKEN_IDENT, 15, 13, "c"},
        {Lexer::TokenType::TOKEN_ADD, 15, 15, "+"},
        {Lexer::TokenType::TOKEN_DECIMAL_INT, 15, 17, "1"},
        {Lexer::TokenType::TOKEN_SEMICOLON, 15, 18, ";"},
        {Lexer::TokenType::TOKEN_R_BRACE, 16, 5, "}"},
        {Lexer::TokenType::TOKEN_IF, 18, 5, "if"},
        {Lexer::TokenType::TOKEN_L_PARENTH, 18, 8, "("},
        {Lexer::TokenType::TOKEN_IDENT, 18, 9, "a"},
        {Lexer::TokenType::TOKEN_LESS, 18, 11, "<"},
        {Lexer::TokenType::TOKEN_IDENT, 18, 13, "b"},
        {Lexer::TokenType::TOKEN_R_PARENTH, 18, 14, ")"},
        {Lexer::TokenType::TOKEN_L_BRACE, 18, 15, "{"},
        {Lexer::TokenType::TOKEN_IDENT, 19, 9, "c"},
        {Lexer::TokenType::TOKEN_ASSIGN, 19, 11, "="},
        {Lexer::TokenType::TOKEN_IDENT, 19, 13, "c"},
        {Lexer::TokenType::TOKEN_ADD, 19, 15, "+"},
        {Lexer::TokenType::TOKEN_DECIMAL_INT, 19, 17, "1"},
        {Lexer::TokenType::TOKEN_SEMICOLON, 19, 18, ";"},
        {Lexer::TokenType::TOKEN_R_BRACE, 20, 5, "}"},
        {Lexer::TokenType::TOKEN_IF, 22, 5, "if"},
        {Lexer::TokenType::TOKEN_L_PARENTH, 22, 8, "("},
        {Lexer::TokenType::TOKEN_IDENT, 22, 9, "a"},
        {Lexer::TokenType::TOKEN_LESS, 22, 11, "<"},
        {Lexer::TokenType::TOKEN_IDENT, 22, 13, "b"},
        {Lexer::TokenType::TOKEN_R_PARENTH, 22, 14, ")"},
        {Lexer::TokenType::TOKEN_L_BRACE, 22, 15, "{"},
        {Lexer::TokenType::TOKEN_IDENT, 23, 9, "c"},
        {Lexer::TokenType::TOKEN_ASSIGN, 23, 11, "="},
        {Lexer::TokenType::TOKEN_IDENT, 23, 13, "c"},
        {Lexer::TokenType::TOKEN_ADD, 23, 15, "+"},
        {Lexer::TokenType::TOKEN_DECIMAL_INT, 23, 17, "1"},
        {Lexer::TokenType::TOKEN_SEMICOLON, 23, 18, ";"},
        {Lexer::TokenType::TOKEN_R_BRACE, 24, 5, "}"},
        {Lexer::TokenType::TOKEN_IF, 26, 5, "if"},
        {Lexer::TokenType::TOKEN_L_PARENTH, 26, 8, "("},
        {Lexer::TokenType::TOKEN_IDENT, 26, 9, "a"},
        {Lexer::TokenType::TOKEN_LESS_OR_EQ, 26, 11, "<="},
        {Lexer::TokenType::TOKEN_IDENT, 26, 14, "b"},
        {Lexer::TokenType::TOKEN_R_PARENTH, 26, 15, ")"},
        {Lexer::TokenType::TOKEN_L_BRACE, 26, 16, "{"},
        {Lexer::TokenType::TOKEN_IDENT, 27, 9, "c"},
        {Lexer::TokenType::TOKEN_ASSIGN, 27, 11, "="},
        {Lexer::TokenType::TOKEN_IDENT, 27, 13, "c"},
        {Lexer::TokenType::TOKEN_ADD, 27, 15, "+"},
        {Lexer::TokenType::TOKEN_DECIMAL_INT, 27, 17, "1"},
        {Lexer::TokenType::TOKEN_SEMICOLON, 27, 18, ";"},
        {Lexer::TokenType::TOKEN_R_BRACE, 28, 5, "}"},
        {Lexer::TokenType::TOKEN_IF, 30, 5, "if"},
        {Lexer::TokenType::TOKEN_L_PARENTH, 30, 8, "("},
        {Lexer::TokenType::TOKEN_IDENT, 30, 9, "a"},
        {Lexer::TokenType::TOKEN_EQUAL, 30, 11, "=="},
        {Lexer::TokenType::TOKEN_IDENT, 30, 14, "b"},
        {Lexer::TokenType::TOKEN_R_PARENTH, 30, 15, ")"},
        {Lexer::TokenType::TOKEN_L_BRACE, 30, 16, "{"},
        {Lexer::TokenType::TOKEN_IDENT, 31, 9, "c"},
        {Lexer::TokenType::TOKEN_ASSIGN, 31, 11, "="},
        {Lexer::TokenType::TOKEN_IDENT, 31, 13, "c"},
        {Lexer::TokenType::TOKEN_ADD, 31, 15, "+"},
        {Lexer::TokenType::TOKEN_DECIMAL_INT, 31, 17, "1"},
        {Lexer::TokenType::TOKEN_SEMICOLON, 31, 18, ";"},
        {Lexer::TokenType::TOKEN_R_BRACE, 32, 5, "}"},
        {Lexer::TokenType::TOKEN_IF, 34, 5, "if"},
        {Lexer::TokenType::TOKEN_L_PARENTH, 34, 8, "("},
        {Lexer::TokenType::TOKEN_IDENT, 34, 9, "a"},
        {Lexer::TokenType::TOKEN_NEQUAL, 34, 11, "!="},
        {Lexer::TokenType::TOKEN_IDENT, 34, 14, "b"},
        {Lexer::TokenType::TOKEN_R_PARENTH, 34, 15, ")"},
        {Lexer::TokenType::TOKEN_L_BRACE, 34, 16, "{"},
        {Lexer::TokenType::TOKEN_IDENT, 35, 9, "c"},
        {Lexer::TokenType::TOKEN_ASSIGN, 35, 11, "="},
        {Lexer::TokenType::TOKEN_IDENT, 35, 13, "c"},
        {Lexer::TokenType::TOKEN_ADD, 35, 15, "+"},
        {Lexer::TokenType::TOKEN_DECIMAL_INT, 35, 17, "1"},
        {Lexer::TokenType::TOKEN_SEMICOLON, 35, 18, ";"},
        {Lexer::TokenType::TOKEN_R_BRACE, 36, 5, "}"},
        {Lexer::TokenType::TOKEN_ELSE, 38, 5, "else"},
        {Lexer::TokenType::TOKEN_L_BRACE, 38, 10, "{"},
        {Lexer::TokenType::TOKEN_IDENT, 39, 9, "c"},
        {Lexer::TokenType::TOKEN_ASSIGN, 39, 11, "="},
        {Lexer::TokenType::TOKEN_IDENT, 39, 13, "c"},
        {Lexer::TokenType::TOKEN_ADD, 39, 15, "+"},
        {Lexer::TokenType::TOKEN_DECIMAL_INT, 39, 17, "1"},
        {Lexer::TokenType::TOKEN_SEMICOLON, 39, 18, ";"},
        {Lexer::TokenType::TOKEN_R_BRACE, 40, 5, "}"},
        {Lexer::TokenType::TOKEN_RETURN, 42, 5, "return"},
        {Lexer::TokenType::TOKEN_IDENT, 42, 12, "c"},
        {Lexer::TokenType::TOKEN_SEMICOLON, 42, 13, ";"},
        {Lexer::TokenType::TOKEN_R_BRACE, 43, 1, "}"},
    };

    Lexer lexer("../../unittests/lexer/code_snippets/all_tokens.paracl");
    const auto& token_list = lexer.get_token_list();

    ASSERT_EQ(token_list.size(), ref_token_list.size());

    for (std::size_t i = 0; i < token_list.size(); ++i) {
        expect_token_eq(token_list[i], ref_token_list[i], i);
    }
}
